init: first test commit
Sadaaaaa/java-explore-with-me pull request #1
Opened 2022-10-06 14:55 UTC by Sadaaaaa

2022-10-11 20:00 UTC, EvgenyKoptubenko commented on db/filmorate.trace.db
> +2022-10-07 11:13:34 jdbc[3]: exception
Для чего этот файл в репозитории?

2022-10-11 20:05 UTC, EvgenyKoptubenko commented on ewm-service/src/main/java/ru/practicum/ewm/compilation/service/CompilationAdminServiceImpl.java
> +                .orElseThrow(() -> new NotFoundException("Compilation is not found!"));
Дублирование в коде. Можно вынести много кода в отдельные методы и использовать их

2022-10-11 20:28 UTC, EvgenyKoptubenko commented on ewm-service/src/main/java/ru/practicum/ewm/exception/ErrorStatus.java
> +    CONTINUE,
Для чего этот Enum?

2022-10-11 20:33 UTC, EvgenyKoptubenko requested changes
Замечаний практически нет. Код сделан хорошо.
Попробуй в документацию добавить инструкцию как запускать проект локально и так же сделать скрипт, который запускает проект локально. Есть еще несколько замечаний по коду, но незначительные

2022-10-11 20:48 UTC, Sadaaaaa commented on db/filmorate.trace.db
> +2022-10-07 11:13:34 jdbc[3]: exception
случайно скопировался, когда смотрел прошлые проекты
удалил

2022-10-11 21:06 UTC, Sadaaaaa commented on ewm-service/src/main/java/ru/practicum/ewm/exception/ErrorStatus.java
> +    CONTINUE,
был в спеке в swagger,
удалил ErrorStatus, заменил на HttpStatus

2022-10-11 22:17 UTC, Sadaaaaa commented on ewm-service/src/main/java/ru/practicum/ewm/compilation/service/CompilationAdminServiceImpl.java
> +                .orElseThrow(() -> new NotFoundException("Compilation is not found!"));
вынес в отдельный метод, к которому обращаюсь, если нужно найти компиляцию

2022-10-11 23:51 UTC, Sadaaaaa commented
Добавил описание в readme.md
скрипт локального запуска не добавлял (не получилось на маке)

2022-10-12 18:02 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо. На будущее, например, когда будут спрашивать на собеседовании, то в проекте еще должно быть:
* 		Healthcheck (отдельный эндпоинт, который возвращает данные о том как себя чувствует приложение) - например описать как работает Spring Actuator
* 		На основе Healthcheck можно делать мониторинг, который будет периодически дергать этот эндпоинт и если что-то в healthcheck сломалось, то присылает алерты
* 		Так же в проекте должна быть документация, которая автоматически собирается - Docsify, например
* 		Так что должно быть отдельное приложение, которое собирает проект, создает артифакт и складывает его в хранилище. В Github тоже можно такое сделать.
* 		Во время код ревью должен подключаться Sonar для проверок.
* 		Во время пул реквеста так же должно подсчитываться покрытие кода тестами
* 		Приложение должно быть защищено, т.е. неавторизованные пользователи не должны иметь доступ к эндпоинтам. Почитай про OAUTH2
* 		В пул реквестах должно быть настроено минимальное количество апруверов, которые должны проверить и заапрувить пул реквест перед тем как его можно мерджить
* 		Все должно быть покрыто юнит тестами, так же должны быть написаны BDD тесты.
* 		Все, что не дает коду пройти в прод называется Quality Gates. К таким quality gates можно причислить: jUnit tests, BDD tests, Sonar, Pull Requests checks, code coverage, Catchpoint tests, Performance tests, Browserstack tests.
* 		Так же в приложении должен быть код, который создает инфраструктуру. Например, если ты хостишься в Amazon, то через Terraform нужно создать инфру.
* 		Дополнительный мониториг бизнес фич. У тебя должны быть графики о том как дела у приложения и у клиентов. И так же настроены алерты, если что-то пошло не так.

2022-10-13 06:09 UTC, merged